/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange operator credentials for an access + refresh token pair.
         *
         *     Rate-limited: repeated failures lock the username out (brute-force guard).
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the currently authenticated operator.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Issue a fresh token pair from a valid refresh token.
         */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run
         * @description Replay a strategy over the requested date range and return the result.
         */
        post: operations["run_api_backtest_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/funding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Funding
         * @description Current futures funding rate for a symbol.
         */
        get: operations["get_funding_api_market_funding_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/klines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Klines
         * @description Candle history — served from the cache, refreshed from Binance.
         */
        get: operations["get_klines_api_market_klines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/orderbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Orderbook
         * @description Order-book depth for a symbol.
         */
        get: operations["get_orderbook_api_market_orderbook_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/tickers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tickers
         * @description Latest 24h tickers — from the live snapshot, or REST as a fallback.
         */
        get: operations["list_tickers_api_market_tickers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/equity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Equity
         * @description Equity-curve history, oldest-first.
         */
        get: operations["equity_api_portfolio_equity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Positions
         * @description Currently open positions across all strategies.
         */
        get: operations["positions_api_portfolio_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description Aggregate accounting — equity, PnL, fees, allocated vs idle capital.
         */
        get: operations["summary_api_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trades
         * @description Most-recent executed trades.
         */
        get: operations["trades_api_portfolio_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Strategies
         * @description Every registered strategy with its allocation, state and PnL.
         */
        get: operations["list_strategies_api_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{name}/allocation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Allocation
         * @description Set a strategy's capital budget; the engine caps its exposure to it.
         */
        patch: operations["update_allocation_api_strategies__name__allocation_patch"];
        trace?: never;
    };
    "/api/strategies/{name}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Strategy
         * @description Close every open position held by the strategy.
         */
        post: operations["close_strategy_api_strategies__name__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{name}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Enabled
         * @description Enable or disable a strategy. Disabling stops new entries only.
         */
        patch: operations["update_enabled_api_strategies__name__enabled_patch"];
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_users__user_id__password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — used by Docker, CI and the deploy script.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllocationUpdate */
        AllocationUpdate: {
            /** Allocated */
            allocated: number | string;
        };
        /** BacktestMetricsRead */
        BacktestMetricsRead: {
            /** Losses */
            losses: number;
            /** Max Drawdown Pct */
            max_drawdown_pct: string;
            /** Sharpe */
            sharpe: string;
            /** Total Return Pct */
            total_return_pct: string;
            /** Trades */
            trades: number;
            /** Win Rate Pct */
            win_rate_pct: string;
            /** Wins */
            wins: number;
        };
        /** BacktestRequest */
        BacktestRequest: {
            /** End */
            end?: string | null;
            /**
             * Fee Rate
             * @default 0.001
             */
            fee_rate: number | string;
            /**
             * Funding Rate
             * @default 0
             */
            funding_rate: number | string;
            /**
             * Initial Capital
             * @default 10000
             */
            initial_capital: number | string;
            /**
             * Slippage Bps
             * @default 2
             */
            slippage_bps: number | string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Strategy */
            strategy: string;
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Candles */
            candles: number;
            /** Equity Curve */
            equity_curve: components["schemas"]["EquityPoint"][];
            /** Final Equity */
            final_equity: string;
            /** Initial Capital */
            initial_capital: string;
            /** Interval */
            interval: string;
            metrics: components["schemas"]["BacktestMetricsRead"];
            /** Net Pnl */
            net_pnl: string;
            /** Strategy */
            strategy: string;
            /** Symbol */
            symbol: string;
            /** Total Fees */
            total_fees: string;
            /** Trades */
            trades: components["schemas"]["BacktestTradeRead"][];
        };
        /** BacktestTradeRead */
        BacktestTradeRead: {
            /** Fee */
            fee: string;
            /** Price */
            price: string;
            /** Quantity */
            quantity: string;
            /** Realized Pnl */
            realized_pnl: string;
            /** Side */
            side: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** Body_login_api_auth_login_post */
        Body_login_api_auth_login_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /**
         * Candle
         * @description A single OHLCV bar for one symbol/interval/market.
         */
        Candle: {
            /** Close */
            close: string;
            /**
             * Close Time
             * Format: date-time
             */
            close_time: string;
            /** High */
            high: string;
            /** Id */
            id?: number | null;
            /** Interval */
            interval: string;
            /** Low */
            low: string;
            /** Market */
            market: string;
            /** Open */
            open: string;
            /**
             * Open Time
             * Format: date-time
             */
            open_time: string;
            /** Symbol */
            symbol: string;
            /** Volume */
            volume: string;
        };
        /** CloseResult */
        CloseResult: {
            /** Closed */
            closed: number;
        };
        /** EnabledUpdate */
        EnabledUpdate: {
            /** Enabled */
            enabled: boolean;
        };
        /** EquityPoint */
        EquityPoint: {
            /** Equity */
            equity: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /**
         * EquitySnapshot
         * @description A point-in-time snapshot of portfolio equity — powers the equity curve.
         */
        EquitySnapshot: {
            /** Equity */
            equity: string;
            /** Fees */
            fees: string;
            /** Id */
            id?: number | null;
            /** Net Pnl */
            net_pnl: string;
            /** Realized Pnl */
            realized_pnl: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Unrealized Pnl */
            unrealized_pnl: string;
        };
        /** FundingRate */
        FundingRate: {
            /** Funding Rate */
            funding_rate: string;
            /** Mark Price */
            mark_price: string;
            /**
             * Next Funding Time
             * Format: date-time
             */
            next_funding_time: string;
            /** Symbol */
            symbol: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Market
         * @enum {string}
         */
        Market: "spot" | "futures";
        /** OrderBook */
        OrderBook: {
            /** Asks */
            asks: components["schemas"]["OrderBookLevel"][];
            /** Bids */
            bids: components["schemas"]["OrderBookLevel"][];
            /** Symbol */
            symbol: string;
        };
        /** OrderBookLevel */
        OrderBookLevel: {
            /** Price */
            price: string;
            /** Qty */
            qty: string;
        };
        /** PasswordReset */
        PasswordReset: {
            /** Password */
            password: string;
        };
        /** PortfolioSummary */
        PortfolioSummary: {
            /** Deployed Capital */
            deployed_capital: string;
            /** Equity */
            equity: string;
            /** Idle Capital */
            idle_capital: string;
            /** Net Pnl */
            net_pnl: string;
            /** Open Positions */
            open_positions: number;
            /** Realized Pnl */
            realized_pnl: string;
            /** Strategies */
            strategies: components["schemas"]["StrategySummary"][];
            /** Total Allocated */
            total_allocated: string;
            /** Total Fees */
            total_fees: string;
            /** Unrealized Pnl */
            unrealized_pnl: string;
        };
        /**
         * Position
         * @description One strategy's position in one symbol/market — the attribution row.
         *
         *     `qty` is always >= 0; `side` gives the direction. `realized_pnl` and
         *     `fees_paid` accumulate over the position's lifetime (the row is kept after
         *     a position goes flat so cumulative PnL is preserved).
         */
        Position: {
            /**
             * Entry Price
             * @default 0
             */
            entry_price: string;
            /**
             * Fees Paid
             * @default 0
             */
            fees_paid: string;
            /** Id */
            id?: number | null;
            /** Market */
            market: string;
            /** Opened At */
            opened_at?: string | null;
            /**
             * Qty
             * @default 0
             */
            qty: string;
            /**
             * Realized Pnl
             * @default 0
             */
            realized_pnl: string;
            /**
             * Side
             * @default flat
             */
            side: string;
            /** Strategy */
            strategy: string;
            /** Symbol */
            symbol: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * Role
         * @description Operator role. `admin` has full access; `user` is restricted
         *     (see plan: Authentication & Roles).
         * @enum {string}
         */
        Role: "admin" | "user";
        /**
         * StrategyRead
         * @description A strategy's identity, lifecycle state and accounting summary.
         */
        StrategyRead: {
            /** Allocated */
            allocated: string;
            /** Enabled */
            enabled: boolean;
            /** Fees */
            fees: string;
            /** Kind */
            kind: string;
            /** Market */
            market: string;
            /** Name */
            name: string;
            /** Net Pnl */
            net_pnl: string;
            /** Open Positions */
            open_positions: number;
            /** Realized Pnl */
            realized_pnl: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Unrealized Pnl */
            unrealized_pnl: string;
        };
        /** StrategySummary */
        StrategySummary: {
            /** Allocated */
            allocated: string;
            /** Fees */
            fees: string;
            /** Net Pnl */
            net_pnl: string;
            /** Open Positions */
            open_positions: number;
            /** Realized Pnl */
            realized_pnl: string;
            /** Strategy */
            strategy: string;
            /** Unrealized Pnl */
            unrealized_pnl: string;
        };
        /** Ticker */
        Ticker: {
            /** Change Pct 24H */
            change_pct_24h: string;
            /** Price */
            price: string;
            /** Quote Volume 24H */
            quote_volume_24h: string;
            /** Symbol */
            symbol: string;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * Trade
         * @description An executed fill — the transaction-log row, attributed to a strategy.
         *
         *     `realized_pnl` is the PnL booked *by this fill* (0 for opening/adding fills,
         *     non-zero when it reduces or closes a position).
         */
        Trade: {
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /**
             * Fee
             * @default 0
             */
            fee: string;
            /** Id */
            id?: number | null;
            /** Market */
            market: string;
            /**
             * Mode
             * @default sim
             */
            mode: string;
            /** Price */
            price: string;
            /** Quantity */
            quantity: string;
            /**
             * Realized Pnl
             * @default 0
             */
            realized_pnl: string;
            /** Side */
            side: string;
            /** Strategy */
            strategy: string;
            /** Symbol */
            symbol: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Password */
            password: string;
            /** @default user */
            role: components["schemas"]["Role"];
            /** Username */
            username: string;
        };
        /** UserInfo */
        UserInfo: {
            /** Role */
            role: string;
            /** Username */
            username: string;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Role */
            role: string;
            /** Username */
            username: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            role?: components["schemas"]["Role"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_backtest_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_funding_api_market_funding_get: {
        parameters: {
            query: {
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundingRate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_klines_api_market_klines_get: {
        parameters: {
            query: {
                symbol: string;
                interval?: string;
                market?: components["schemas"]["Market"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candle"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orderbook_api_market_orderbook_get: {
        parameters: {
            query: {
                symbol: string;
                market?: components["schemas"]["Market"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderBook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickers_api_market_tickers_get: {
        parameters: {
            query?: {
                market?: components["schemas"]["Market"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticker"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    equity_api_portfolio_equity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquitySnapshot"][];
                };
            };
        };
    };
    positions_api_portfolio_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Position"][];
                };
            };
        };
    };
    summary_api_portfolio_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
        };
    };
    trades_api_portfolio_trades_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trade"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRead"][];
                };
            };
        };
    };
    update_allocation_api_strategies__name__allocation_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_strategy_api_strategies__name__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_enabled_api_strategies__name__enabled_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnabledUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_users__user_id__password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
