"""add candle cache table

Revision ID: 0003
Revises: 0002
Create Date: 2026-05-20 22:14:35.005675
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('interval', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'symbol', 'interval', 'open_time', name='uq_candle_bar')
    )
    op.create_index(op.f('ix_candle_interval'), 'candle', ['interval'], unique=False)
    op.create_index(op.f('ix_candle_market'), 'candle', ['market'], unique=False)
    op.create_index(op.f('ix_candle_open_time'), 'candle', ['open_time'], unique=False)
    op.create_index(op.f('ix_candle_symbol'), 'candle', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candle_symbol'), table_name='candle')
    op.drop_index(op.f('ix_candle_open_time'), table_name='candle')
    op.drop_index(op.f('ix_candle_market'), table_name='candle')
    op.drop_index(op.f('ix_candle_interval'), table_name='candle')
    op.drop_table('candle')
    # ### end Alembic commands ###
