"""add position and strategy_allocation tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-05-20 22:53:01.548400
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fees_paid', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy', 'market', 'symbol', name='uq_position')
    )
    op.create_index(op.f('ix_position_strategy'), 'position', ['strategy'], unique=False)
    op.create_index(op.f('ix_position_symbol'), 'position', ['symbol'], unique=False)
    op.create_table('strategy_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('allocated', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_allocation_strategy'), 'strategy_allocation', ['strategy'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_allocation_strategy'), table_name='strategy_allocation')
    op.drop_table('strategy_allocation')
    op.drop_index(op.f('ix_position_symbol'), table_name='position')
    op.drop_index(op.f('ix_position_strategy'), table_name='position')
    op.drop_table('position')
    # ### end Alembic commands ###
