"""add trade table

Revision ID: 0005
Revises: 0004
Create Date: 2026-05-20 23:01:37.968750
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fee', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_executed_at'), 'trade', ['executed_at'], unique=False)
    op.create_index(op.f('ix_trade_strategy'), 'trade', ['strategy'], unique=False)
    op.create_index(op.f('ix_trade_symbol'), 'trade', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_symbol'), table_name='trade')
    op.drop_index(op.f('ix_trade_strategy'), table_name='trade')
    op.drop_index(op.f('ix_trade_executed_at'), table_name='trade')
    op.drop_table('trade')
    # ### end Alembic commands ###
