"""add equity_snapshot table

Revision ID: 0006
Revises: 0005
Create Date: 2026-05-21 00:57:24.386026
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('equity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_snapshot_ts'), 'equity_snapshot', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equity_snapshot_ts'), table_name='equity_snapshot')
    op.drop_table('equity_snapshot')
    # ### end Alembic commands ###
